P2/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Entities;
using P2.Products;
using P2.Utils;

namespace P2.Controllers
{
    public class ProductController : Controller
    {
       
        // GET: Product
        public async Task<ActionResult> Index()
        {
            ProductsClient api = new ProductsClient();

            return View(api.GetAll());
        }
        
        // get: Product/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: product/create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Product product)
        {
            if (ModelState.IsValid)
            {
                ProductsClient api = new ProductsClient();
                
                await api.AddAsync(product);
                
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: product/edit/5
        public async Task<ActionResult> Edit(int id)
        {
            ProductsClient api = new ProductsClient();

            Product product = await api.GetAsync(id);

            if (product == null)
            {
                return HttpNotFound();
            }

            return View(product);
        }

        // Post: Product/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                ProductsClient api = new ProductsClient();

                await api.UpdateAsync(product);

                return RedirectToAction("Index");
            }

            return View(product);
        }

        public async Task<ActionResult> Delete(int id)
        {
            ProductsClient api = new ProductsClient();

            Product product = api.Get(id);

            if (product == null)
            {
                return HttpNotFound();
            }

            return View(product);
        }

        // Post: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            ProductsClient api = new ProductsClient();

            await api.DeleteAsync(id);

            return RedirectToAction("Index");
        }

        

    }
}

P2/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Entities;
using P2.Models;
using P2.Users;
using P2.UserTypes;
using P2.Utils;

namespace P2.Controllers
{
    public class UserController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: User
        public async Task<ActionResult> Index()
        {
            UsersClient api = new UsersClient();
            
            return View(await api.GetAllAsync());
        }

        // GET: User/Create
        public async Task<ActionResult> Create()
        {
            ViewBag.UserTypeID = LoadUserTypes();
            return View();
        }

        // POST: User/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(User user)
        {
            if (ModelState.IsValid)
            {

                UsersClient api = new UsersClient();

                user.Password = Utilities.SHA256Encrypt(user.Password);

                await api.AddAsync(user);

                return RedirectToAction("Index");
            }

            ViewBag.UserTypeID = LoadUserTypes();
            return View(user);
        }

        // GET: User/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            UsersClient api = new UsersClient();

            User user = await api.GetAsync(id);

            if (user == null)
            {
                return HttpNotFound();
            }

            ViewBag.UserTypeID = LoadUserTypes();

            return View(user);
        }

        // POST: User/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(User user)
        {
            if (ModelState.IsValid)
            {
                UsersClient api = new UsersClient();

                await api.UpdateAsync(user);

                return RedirectToAction("Index");
            }

            ViewBag.UserTypeID = LoadUserTypes();

            return View(user);
        }

        // GET: User/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            UsersClient api = new UsersClient();

            User user = await api.GetAsync(id);

            if (user == null)
            {
                return HttpNotFound();
            }

            return View(user);
        }

        // POST: User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            UsersClient api = new UsersClient();
            await api.DeleteAsync(id);

            return RedirectToAction("Index");
        }
        
        private SelectList LoadUserTypes()
        {
            UserTypesClient api = new UserTypesClient();

            UserType[] userTypes = api.GetAll();

            return new SelectList(userTypes, "Id", "Name");
        }
    }
}

P2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - La Oliva de Italia</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("La Oliva de Italia", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Productos", "Index", "Product")</li>
                    <li>@Html.ActionLink("Usuarios", "Index", "User")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div>
        @RenderBody()
    </div>
    <div class="container body-content">
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Carlos Castro Brenes</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        $(document).ready(function () {
            $('.carousel').carousel()
        });

    </script>

</body>
</html>